// src/components/Sidebar/Sidebar.tsx
import React, {FC, useEffect, useState} from 'react';
import {Link, NavLink} from 'react-router-dom';
import routes from '../../routes';
import Title from '../../typography/Title';
import Download from '../Download';
import svgTypescript from '../../assets/images/typescript.svg';
import svgJavascript from '../../assets/images/javascript.svg';

interface SidebarProps {
    onLinkClick?(): void;
}

const Sidebar: FC<SidebarProps> = ({onLinkClick}) => {
    const [search, setSearch] = useState<string>('');

    return (
        <aside className='space-y-4 flex flex-col w-72 h-screen px-4 py-8 overflow-y-auto bg-white border-r rtl:border-r-0 rtl:border-l dark:bg-gray-900 dark:border-gray-700'>
            <Link to='/' className='flex gap-1 items-center' onClick={() => (onLinkClick ? onLinkClick() : {})}>
                <img className='w-auto h-6 sm:h-7' src={svgTypescript} alt='' />
                <img className='w-auto h-6 sm:h-7' src={svgJavascript} alt='' />
                <Title title='Functions' />
            </Link>

            <div className='flex flex-col justify-between flex-1 gap-4'>
                <div>
                    <input
                        type='search'
                        placeholder='Search function'
                        className='border rounded p-2 w-full outline-none'
                        value={search}
                        onChange={(event: any) => setSearch(event.target.value)}
                    />
                </div>

                <nav className='space-y-2'>
                    {routes
                        .map((f) => f.path.split('/').join(''))
                        .filter((link: string) => (search ? link.toLowerCase().includes(search.toLowerCase()) : true))
                        .sort()
                        .map((link: string, key: number) => (
                            <NavLink
                                className={({isActive, isPending}) =>
                                    `block px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-md dark:bg-gray-800 dark:text-gray-200${
                                        isActive ? ' bg-gray-100' : ''
                                    }`
                                }
                                to={`/${link}`}
                                key={key}
                                onClick={() => (onLinkClick ? onLinkClick() : {})}
                            >
                                <span className='font-medium text-xs'>{link}</span>
                            </NavLink>
                        ))}

                    <hr className='border-gray-200 dark:border-gray-600' />
                </nav>

                <a href='https://github.com/dsabre' target='_blank' className='flex items-center px-4 -mx-2'>
                    <img
                        className='object-cover mx-2 rounded-full h-9 w-9'
                        src='https://github.com/dsabre.png'
                        alt='avatar'
                    />
                    <span className='mx-2 font-medium text-gray-800 dark:text-gray-200'>Daniele Sabre</span>
                </a>
            </div>
        </aside>
    );
};

export default Sidebar;

// src/components/Sidebar.vue
<script setup>
import {RouterLink} from 'vue-router';
import {ref, watch} from 'vue';
import {routes} from '../router';

const getFunctions = () => routes.filter((r) => r.path.startsWith('/f/'));
const functions = ref(getFunctions());
const functionsFilter = ref(getFunctions());
const search = ref('');
const getClonedObject = (object) => JSON.parse(JSON.stringify(object));

watch(search, () => {
    if (search.value.trim() === '') {
        functionsFilter.value = getClonedObject(functions.value);
    } else {
        functionsFilter.value = getClonedObject(
            functions.value.filter((f) => f.name.trim().toLowerCase().includes(search.value.trim().toLowerCase()))
        );
    }
});
</script>

<template>
    <button
        data-drawer-target="default-sidebar"
        data-drawer-toggle="default-sidebar"
        aria-controls="default-sidebar"
        type="button"
        class="inline-flex items-center p-2 mt-2 ml-3 text-sm text-gray-500 rounded-lg sm:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
    >
        <span class="sr-only">Open sidebar</span>
        <svg
            class="w-6 h-6"
            aria-hidden="true"
            fill="currentColor"
            viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg"
        >
            <path
                clip-rule="evenodd"
                fill-rule="evenodd"
                d="M2 4.75A.75.75 0 012.75 4h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 4.75zm0 10.5a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zM2 10a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 10z"
            ></path>
        </svg>
    </button>

    <aside
        id="default-sidebar"
        class="fixed top-0 left-0 z-40 w-64 h-screen transition-transform -translate-x-full sm:translate-x-0 shadow"
        aria-label="Sidenav"
    >
        <div
            class="overflow-y-auto py-5 px-3 h-full bg-gray-50 border-r border-gray-200 dark:bg-gray-800 dark:border-gray-700"
        >
            <RouterLink to="/" class="flex items-center pl-2 mb-5 space-x-3">
                <div class="flex gap-1">
                    <img src="@/assets/images/typescript.svg" class="h-6 sm:h-8" alt="TS" />
                    <img src="@/assets/images/javascript.svg" class="h-6 sm:h-8" alt="JS" />
                </div>
                <span class="self-center text-2xl font-semibold whitespace-nowrap text-gray-900 dark:text-white"
                    >Functions</span
                >
            </RouterLink>
            <form class="flex items-center mb-4">
                <label for="simple-search" class="sr-only">Search</label>
                <div class="relative w-full">
                    <div class="flex absolute inset-y-0 left-0 items-center px-3 pointer-events-none">
                        <svg
                            class="w-5 h-5 text-gray-500 dark:text-gray-400"
                            aria-hidden="true"
                            xmlns="http://www.w3.org/2000/svg"
                            fill="none"
                            viewBox="0 0 20 20"
                        >
                            <path
                                stroke="currentColor"
                                stroke-linecap="round"
                                stroke-linejoin="round"
                                stroke-width="2"
                                d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"
                            />
                        </svg>
                    </div>
                    <input
                        type="search"
                        id="simple-search"
                        class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full pl-10 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light"
                        placeholder="Search function"
                        required=""
                        v-model="search"
                    />
                </div>
            </form>
            <ul class="space-y-2">
                <li v-for="item in functionsFilter">
                    <RouterLink
                        :to="item.path"
                        class="flex items-center p-2 text-base font-normal text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
                    >
                        <svg
                            class="w-[12px] h-[12px] text-gray-800 dark:text-white"
                            aria-hidden="true"
                            xmlns="http://www.w3.org/2000/svg"
                            fill="currentColor"
                            viewBox="0 0 10 16"
                        >
                            <path
                                d="M3.414 1A2 2 0 0 0 0 2.414v11.172A2 2 0 0 0 3.414 15L9 9.414a2 2 0 0 0 0-2.828L3.414 1Z"
                            />
                        </svg>
                        <span class="ml-3">{{ item.name }}</span>
                    </RouterLink>
                </li>
            </ul>
        </div>
        <div class="absolute bottom-0 left-0 justify-center p-4 w-full z-20">
            <a
                href="https://github.com/dsabre"
                target="_blank"
                class="flex justify-between items-center p-2 my-4 w-full rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700"
            >
                <span class="sr-only">Show GitHub profile</span>
                <div class="flex items-center space-x-3">
                    <img src="https://github.com/dsabre.png" class="w-8 h-8 rounded-full" alt="Bonnie avatar" />
                    <div class="text-left">
                        <div class="font-semibold leading-none text-gray-900 dark:text-white mb-0.5">Daniele Sabre</div>
                    </div>
                </div>
            </a>
        </div>
    </aside>
</template>
